apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-backuper
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: todo-backuper
              image: todo-backuper
              resources:
                requests:
                  memory: "50Mi"
                  cpu: "10m"
                limits:
                  memory: "250Mi"
                  cpu: "50m"
              imagePullPolicy: IfNotPresent
              env:
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret
                      key: postgres_password
                - name: POSTGRES_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: postgres-config
                      key: postgres_host
                - name: POSTGRES_PORT
                  valueFrom:
                    configMapKeyRef:
                      name: postgres-config
                      key: postgres_port
                - name: POSTGRES_USER
                  valueFrom:
                    configMapKeyRef:
                      name: postgres-config
                      key: postgres_user
                - name: POSTGRES_DB
                  valueFrom:
                    configMapKeyRef:
                      name: postgres-config
                      key: postgres_db
                - name: BUCKET_NAME
                  value: dwk-backups123
                - name: GOOGLE_APPLICATION_CREDENTIALS
                  value: /secrets/gcp-key.json
              volumeMounts:
                - name: gcp-credentials
                  mountPath: /secrets
                  readOnly: true
          volumes:
            - name: gcp-credentials
              secret:
                secretName: gcp-credentials
          restartPolicy: OnFailure
