apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml
namespace: staging

patches:
- target:
    kind: Deployment
    name: todo-broadcaster
  path: todo-broadcaster-dep.yaml