apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-broadcaster
spec:
  template:
    spec:
      containers:
        - name: todo-broadcaster
          env:
            - name: ENV
              value: staging
