apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-generator
spec:
  schedule: "33 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: todo-generator
              image: todo-generator
              imagePullPolicy: IfNotPresent
              resources:
                requests:
                  memory: "50Mi"
                  cpu: "10m"
                limits:
                  memory: "250Mi"
                  cpu: "50m"
              env:
                - name: TODO_BACKEND_URL
                  valueFrom:
                    configMapKeyRef:
                      name: project-config
                      key: todo_backend_url
          restartPolicy: OnFailure
