apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-broadcaster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-broadcaster
  template:
    metadata:
      labels:
        app: todo-broadcaster
    spec:
      containers:
        - name: todo-broadcaster
          image: todo-broadcaster
          resources:
            requests:
              memory: "50Mi"
              cpu: "10m"
            limits:
              memory: "250Mi"
              cpu: "50m"
          env:
            - name: NATS_URL
              value: nats://my-nats.default.svc.cluster.local:4222
            - name: DISCORD_WEBHOOK
              valueFrom:
                secretKeyRef:
                  name: discord-webhook
                  key: DISCORD_WEBHOOK
                  optional: true